// <auto-generated />
namespace Octo.Net.Data1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Revert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Revert));
        
        string IMigrationMetadata.Id
        {
            get { return "201910291804332_Revert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
